name: "Gemini AI Code Reviewer"
description: "This GitHub Action automatically reviews PRs using Google's Gemini AI model."
author: 'truongnh1992'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to interact with the repository'
    required: true
  GEMINI_API_KEY:
    description: 'Google Gemini API key'
    required: true
  GEMINI_MODEL:
    description: 'The Gemini model to use for code review'
    required: false
    default: 'gemini-1.5-flash-002'
  EXCLUDE:
    description: 'Comma-separated list of file patterns to exclude'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v4

  - name: Checkout MCP server repository
    uses: actions/checkout@v3
    with:
      repository: github/github-mcp-server
      path: github-mcp-server

  - name: Set up Go
    uses: actions/setup-go@v3
    with:
      go-version: '1.23' # Adjust based on MCP server requirements

  - name: Build MCP server
    shell: bash
    run: |
      cd github-mcp-server/cmd/github-mcp-server
      go build -o github-mcp-server

  - name: Set up Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '18'

  - name: Install dependencies for MCP client
    shell: bash
    run: |
      cd ${{ github.action_path }}/tools
      npm install

  - name: Run code review
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      GEMINI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
      GEMINI_MODEL: gemini-1.5-pro-002 # Optional, default is `gemini-1.5-flash-002`
      EXCLUDE: ${{ inputs.EXCLUDE }}
    run: node ${{ github.action_path }}/tools/mcp_client.js
