name: AI Code Review

on:
  issue_comment:
    types: [created]

permissions: write-all
jobs:
  ai_code_review:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && github.event.comment.body == '/review'
    steps:
      - name: Checkout MCP server repository
        uses: actions/checkout@v3
        with:
          repository: github/github-mcp-server
          path: github-mcp-server

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'  # Adjust based on MCP server requirements

      - name: Build MCP server
        run: |
          cd github-mcp-server/cmd/github-mcp-server
          go build -o github-mcp-server

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies for MCP client
        run: |
          mkdir -p tools
          echo '{"name": "mcp-client", "version": "1.0.0", "dependencies": {"axios": "^0.21.1", "parse-diff": "^0.9.0"}}' > tools/package.json
          cd tools
          npm install

      - name: Run MCP client script
        run: node tools/mcp_client.js
        env:
          MCP_PAT: ${{ secrets.MCP_PAT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.issue.number }}